client/src/App.jsx
client/src/components/Activity/Activity.css
client/src/components/Header/Header.css
client/src/components/Header/Header.jsx
client/src/components/Navigation/Navigation.css
client/src/layouts/HomeLayout.css
client/src/layouts/HomeLayout.jsx
client/src/pages/Home/HomePage.jsx

Fixed some Layout component and CSS styling issues to resolve graphical bug on homepage.

MENEX-3 Fixed HomePage components

---

client/src/components/Posts/Post/Post.css
client/src/components/Posts/Post/Post.jsx

Added a Follow button to user Posts

MENEX-28: Add Follow Button to Posts

---

client/src/api/config.js
client/src/api/hooks/useGetPosts.js
client/src/components/Activity/Activity.jsx
client/src/pages/Home/Home.jsx
server/src/app.js

Updated Home Feed with Followed User's Posts

feature/MENEX-30: Update Home Feed

---

client/src/components/Posts/Post/Post.css
client/src/components/Posts/Post/Post.jsx

Added the ability to navigate to user's profile page by clicking on their displayname or handle from posts.

MENEX-41: Add Nav to Profile via Post

---

client/src/components/Header/Header.css
client/src/components/Header/Header.jsx
client/src/components/Search/Search.css
client/src/components/Search/Search.jsx

Added search bar component, currently located in the Header.

MENEX-44: Add Search Component

---

server/src/app.js

Implemented API Logic for Search functionality.

MENEX-45: Implement API Logic for Search

---

client/src/components/ProfileCard/ProfileCard.css
client/src/components/ProfileCard/ProfileCard.jsx
client/src/pages/Search/Search.css
client/src/pages/Search/Search.jsx
server/src/app.js

Added ProfileCard to gracefully display user search results. Updated display for Posts in search results as well.

feature/MENEX-47: Add ProfileCard for Search Results

---

client/src/App.jsx
client/src/api/config.js
client/src/api/hooks/useSearch.js
client/src/components/Header/Header.css
client/src/components/Header/Header.jsx
client/src/components/ProfileCard/ProfileCard.css
client/src/components/ProfileCard/ProfileCard.jsx
client/src/components/Search/Search.css
client/src/components/Search/Search.jsx
client/src/layouts/SearchLayout/SearchLayout.css
client/src/layouts/SearchLayout/SearchLayout.jsx
client/src/pages/Search/Search.css
client/src/pages/Search/Search.jsx
client/src/pages/Search/SearchPage.jsx
server/src/app.js

Implemented search functionality for Users and Posts. Searching by keyword will return all User and Posts results that share that keyboard. Can filter results by type (User, Post, all).

Feature/MENEX-43: implement search functionality

---

client/src/components/Comments/Comment/Comment.jsx
client/src/components/Posts/Post/Post.css
client/src/components/Posts/Post/Post.jsx
client/src/pages/Home/Home.jsx
client/src/pages/UserProfile/UserProfile.jsx

MENEX-51: Add Comment Component

---

client/src/components/Comments/CommentForm/CommentForm.jsx

feature/MENEX-52: Add CommentForm Component

---

client/src/api/config.js
client/src/api/hooks/useCreateComment.js
client/src/api/hooks/useDeleteComment.js
client/src/api/hooks/useEditComment.js
client/src/api/hooks/useGetComments.js
client/src/components/Comments/Comment/Comment.css
client/src/components/Comments/Comment/Comment.jsx
client/src/components/Comments/CommentForm/CommentForm.css
client/src/components/Comments/CommentForm/CommentForm.jsx
client/src/components/Posts/Post/Post.css
client/src/components/Posts/Post/Post.jsx
client/src/pages/Home/Home.jsx
client/src/pages/Search/Search.jsx
client/src/pages/UserProfile/UserProfile.jsx
client/src/utils/apiUtils.js
server/src/app.js

Implemented API logic and custom hooks to support commenting system.

feature/MENEX-50: Implement API Logic for Comments

---

client/src/components/Comments/Comment/Comment.jsx
client/src/components/Posts/Post/Post.jsx
client/src/pages/Home/Home.jsx
client/src/pages/Search/Search.jsx
client/src/pages/UserProfile/UserProfile.jsx

Implemented a permissions check by setting isOwned based on matching user_id to session user_id. This manages whether a user has the permission to edit/delete a post/comment.

MENEX-57: Implement User Permissions Check

---

client/src/api/config.js
client/src/api/hooks/useNotificationsWebSocket.js
client/src/components/Header/Header.jsx
client/src/components/Notifications/NotificationsTray/NotificationsTray.jsx
server/package-lock.json
server/package.json
server/src/app.js

Installed 'ws' WebSocket library, instantiated a WebSocket Server, and updated Notifications to be handled via WebSockets for real time notifications.

MENEX-67: Update Notifications to WebSockets

---

client/src/api/config.js
client/src/api/hooks/useUpdateProfileSettings.js
client/src/components/Settings/ProfileSettings/ProfileSettings.jsx
server/src/app.js

Added functionality for Profile settings allowing users to update display name, handle, profile name, bio, and location.

feature/MENEX-35: Add UserSettings Profile Update

---

client/src/App.jsx
client/src/layouts/MessagesLayout/MessagesLayout.css
client/src/layouts/MessagesLayout/MessagesLayout.jsx
client/src/pages/Messages/MessagesPage.jsx

Added MessagesLayout and MessagesPage.

MENEX-76: Add Messages Page

---

client/src/components/Messaging/Message/Message.jsx
client/src/components/Messaging/MessageForm/MessageForm.jsx

Added Message and MessageForm components.

MENEX-79: Add Message Component

---

client/src/api/config.js
client/src/api/hooks/useCreateConversation.js
client/src/api/hooks/useCreateMessage.js
client/src/api/hooks/useGetConversations.js
client/src/api/hooks/useGetMessages.js
client/src/api/hooks/useGetUser.js
client/src/api/hooks/useMessagesWebSocket.js
client/src/api/hooks/useSetMessagesAsRead.js
client/src/api/hooks/useUpdateConversationParticipants.js
client/src/components/Messaging/Conversations/Conversation/Conversation.css
client/src/components/Messaging/Conversations/Conversation/Conversation.jsx
client/src/components/Messaging/Conversations/ConversationMenu/ConversationMenu.css
client/src/components/Messaging/Conversations/ConversationMenu/ConversationMenu.jsx
client/src/components/Messaging/Message/Message.css
client/src/components/Messaging/Message/Message.jsx
client/src/components/Messaging/MessageForm/MessageForm.css
client/src/components/Messaging/MessageForm/MessageForm.jsx
client/src/layouts/MessagesLayout/MessagesLayout.css
client/src/layouts/MessagesLayout/MessagesLayout.jsx
client/src/pages/Messages/MessagesPage.jsx
client/src/utils/apiUtils.js
server/src/app.js

Implemented API logic for messaging system.

MENEX-80: Implement Messaging API Logic

---

database/menexus_schema.sql

Updated database schema script to reflect changes made to the schema to support the messaging system.

MENEX-81: Update Database Schema Script

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/api/config.js
client/src/api/hooks/useGenerateCryptoKeys.js
client/src/components/RegisterForm/RegisterFormPKI.css
client/src/components/RegisterForm/RegisterFormPKI.jsx
client/src/pages/Register/RegisterPagePKI.jsx

Implemented Public/Private key generation utilizing @noble/secp256k1

MENEX-85: Implement Crypto Key Pair Generation

---

client/src/api/config.js
client/src/api/hooks/useGenerateCryptoKeys.js
client/src/components/RegisterForm/RegisterFormPKI.jsx
database/example-database.js
database/orbitdb-service.js
database/userPublicKeys.js
server/src/app.js
server/src/controllers/authController.js
server/src/models/user.js
server/src/routes/authRoutes.js

Implemented orbitDB decentralized database, public key storage, and userId retrieval based on public key search.

MENEX-86: Setup Decentralized Database

---

synapse/config/libp2p.js
synapse/package.json

Configured libp2pInstance for use by Synapse

MENEX-97: Configure Libp2p Instance

---

protocols/snp/actionTypes.js
protocols/snp/index.js
protocols/snp/messageTypes.js
protocols/snp/messageUtils.js
protocols/snp/resourceTypes.js
protocols/snp/version.js

Created first definitions of the Synaptic Nexus Protocol. Included utilities for creating, encoding, decoding, and validating messages. Defined supported message types, action types, and resource types.

MENEX-98: Define SNP

---

client/src/components/Comments/CommentForm/CommentForm.jsx
client/src/components/Header/Header.jsx
client/src/components/Notifications/Notification/Notification.jsx
client/src/layouts/PostLayout/PostLayout.jsx
client/src/pages/Post/PostObject.jsx

Fixed Notification useEffect() bug
Fixed Notification being created when commenting on owned posts

Fixed Notification useEffect() bug

---

meNexus/web/src/App.jsx
meNexus/web/src/api/config.js
meNexus/web/src/api/hooks/useGetSynapseMetadata.js
meNexus/web/src/api/hooks/useGetSynapsePosts.js
meNexus/web/src/components/Header/Header.jsx
meNexus/web/src/layouts/SynapseLayout/SynapseExploreLayout.jsx
meNexus/web/src/layouts/SynapseLayout/SynapseLayout.jsx
meNexus/web/src/pages/Synapse/Synapse.jsx
meNexus/web/src/pages/Synapse/SynapseExplorePage.jsx
meNexus/web/src/pages/Synapse/SynapsePage.jsx
synapse/api/config/endpoints.js
synapse/api/src/controllers/synapseController.js
synapse/api/src/controllers/userController.js
synapse/api/src/models/post.js
synapse/api/src/routes/synapseRoutes.js
synapse/protocols/snp/resourceTypes.js
synapse/src/messenger.js

Implemented SynapsePage which renders all posts for a given Synapse by publicKey

Menex 107 implement synapse page

---

apps/client-web/src/layouts/SettingsLayout/SettingsLayout.jsx

- settings layout was mounting ProfileSettings twice (desktop/mobile) instead of mounting the component conditionally

fix profile picture upload
